### ISSUE TITLE
NotSupportedError: Failed to set the 'playbackRate' property on 'HTMLMediaElement': The provided playback rate (-0.5...

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/codingblocks.online.projectx#246]
http://sentry.cb.lk/sentry/v2-prod/issues/2638/

```
NotSupportedError: Failed to set the 'playbackRate' property on 'HTMLMediaElement': The provided playback rate (-0.5) is not in the supported playback range.
  at o.changeSpeed (/assets/codingblocks-online-0576319dfe1cc6960c28b9a42e9e01a2.js:239:30)
  at o.send (/assets/vendor-43c5b905c81bb7f191b90a7de01b2b8d.js:3323:15)
  at o.n [as send] (/assets/vendor-43c5b905c81bb7f191b90a7de01b2b8d.js:3281:9)
  at o.down (/assets/codingblocks-online-0576319dfe1cc6960c28b9a42e9e01a2.js:232:5213)
  at g (/assets/vendor-43c5b905c81bb7f191b90a7de01b2b8d.js:6620:408)
...
(4 additional frame(s) were not displayed)
```

**Comment by abhishek97** [comment]
We shouldn't allow playback rate to be `0` anyways, that's a pause. Make sure the playback rate is ` > 0` @VibhorCodecianGupta @architkshk

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 done
